apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: frontend
spec:
  podSelector:
    matchLabels:
            app: webserver
  egress:
    - to:
            - podSelector:           
                matchLabels:
                  app: mysql
