apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: role-binding
        namespace: user
subjects:
        - kind: User
          name: sid
          apiGroup: rbac.authorization.k8s.io
roleRef:
        kind: Role
        name: network-admin
        apiGroup: rbac.authorization.k8s.io
