apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
        name: network-admin
        namespace: user
rules:
        - apiGroups: ["networking.k8s.io"]
          resources: ["networkpolicies"]
          verbs: ["get","create","list","update","watch","delete"]


