apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenyingress
spec:
  crd:
    spec:
      names:
        kind: K8sDenyIngress
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyingress 
        violation [{"msg": msg}] {
          some i
          input.review.object.kind == "NetworkPolicy"
          input.review.object.spec.ingress[i].from[i].podSelector.matchLabels.type == "frontend"
          msg := "frontend is not allowed"

        }

